version: '3'
services:
  api:
    build: .
    # command: npm run start:dev
    ports:
      - "8080:8080"
    tty: true
    volumes:
      - ./:/app/
      - node_modules:/app/node_modules

volumes:
  node_modules:
